env:
  global:
    - FREECAD_RELEASE="0.18"
    - DEPLOY_RELEASE=${DEPLOY_RELEASE:-$FREECAD_RELEASE}
    - OSX_PORTS_CACHE=${OSX_PORTS_CACHE:-FreeCAD/FreeCAD-ports-cache}
    - DEPLOY_REPO=${DEPLOY_REPO:-FreeCAD/FreeCAD}
    - DEPLOY=${DEPLOY:-0}

os: linux
compiler: gcc
language: cpp

before_install:
   - sudo apt-get update -qq && sudo apt-get install -y desktop-file-utils jq
   - curl -LO "https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64"
   - chmod +x jq-linux64 && sudo mv jq-linux64 $(which jq)

install:
   - eval "$(curl -fsSL "https://raw.githubusercontent.com/${OSX_PORTS_CACHE}/v${FREECAD_RELEASE}/travis-helpers.sh")"
   - curl -LO https://raw.githubusercontent.com/AppImage/AppImages/master/pkg2appimage
   # Conda
   - wget "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage"
   - chmod a+x appimagetool-x86_64.AppImage
   - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
   - bash miniconda.sh -b -p $HOME/miniconda
   - export PATH="$HOME/miniconda/bin:$PATH"
   - hash -r
   - conda config --set always_yes yes --set changeps1 no
   - conda config --add channels conda-forge
   - conda update -q conda
   - source activate root

script:
   # PPA Py2Qt4
   - bash -ex ./pkg2appimage FreeCAD-Daily
   - out/*.AppImage --console $TRAVIS_BUILD_DIR/out/version.py
   # Conda Py3Qt5
   - cd conda
   - bash ./conda.sh
   - cd ..

after_success:
   - |
     if [ "${DEPLOY}" == "1" ]; then
        # PPA Py2Qt4
        export DEPLOYMENT_ARCHIVE=$(ls out/*.AppImage)
        export deployContext=$(create_helper_context repo=${DEPLOY_REPO} auth_token=${GH_TOKEN} release=${DEPLOY_RELEASE})
        gitHub_deploy_asset_to_release_named $deployContext ${DEPLOYMENT_ARCHIVE}
        gitHub_prune_assets_for_release_named $deployContext "glibc2.17-x86_64.AppImage" 1
        # Conda Py3Qt5
        export DEPLOYMENT_ARCHIVE=$(ls conda/*.AppImage)
        export deployContext=$(create_helper_context repo=${DEPLOY_REPO} auth_token=${GH_TOKEN} release=${DEPLOY_RELEASE})
        gitHub_deploy_asset_to_release_named $deployContext ${DEPLOYMENT_ARCHIVE}
        gitHub_prune_assets_for_release_named $deployContext "glibc2.12-x86_64.AppImage" 1
     fi
