# This is a basic workflow to help you get started with Actions

name: source_creation

# Controls when the workflow will run
on:
  schedule:
   - cron: "* 0/4 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ["0.21rc1a"]
        branch: ["0.21rc1a"]

    steps:
      - name: Run a multi-line script
        run: |
          git clone https://github.com/FreeCAD/FreeCAD
          touch freecad_version.txt
          wget https://raw.githubusercontent.com/FreeCAD/FreeCAD-Bundle/${GITHUB_REF##*/}/make_version_file.py
          cd FreeCAD
          git checkout ${{ matrix.branch }}
          python ../make_version_file.py ../freecad_version.txt
          git archive HEAD -o ../freecad_source.tar.gz
          
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: freecad*
          tag: ${{ matrix.tag }}
          overwrite: true
          file_glob: true
